  sensors:
    image: migruiz/clima-sensors-rpi3:climav2
    container_name: clima-sensors-climav2
    volumes:
     - sensorsfs:/sys/fs/cgroup
    environment:
        MQTTLOCAL : mqtt://192.168.1.6
        NODEID : 4
    restart: always
    privileged: true