version: '2'
services:
  mqtt:
    image: migruiz/clima-queue-rpi3:climav2
    container_name: clima-queue-climav2
    volumes:
     - mqttfs:/sys/fs/cgroup
    ports:
     - "1883:1883"
    restart: always
    
  sensors:
    image: migruiz/clima-sensors-rpi3:climav2
    container_name: clima-sensors-climav2
    volumes:
     - sensorsfs:/sys/fs/cgroup
    environment:
        MQTTLOCAL : mqtt://clima-queue-climav2
        NODEID : 1
    restart: always
    privileged: true
    
  datacollector:
    image: migruiz/clima-datacollector-rpi3:climav2
    container_name: clima-datacollector
    volumes:
     - datacollectorfs:/sys/fs/cgroup
    environment:
        MQTTLOCAL : mqtt://clima-queue-climav2
    restart: always
    
