version: '2'
services:
  sensors:
    extends:
        file: common-services.yml
        service: common
    image: migruiz/clima-sensors-zero
    container_name: clima-sensors
    restart: always
    privileged: true
    
