version: '2'
services:
  sensors:
    image: migruiz/clima-sensors-zero:r1
    container_name: clima-sensors
    environment:
        TEMPQUEUEURL : amqp://pi:pi@192.168.1.14
        NODEID : 2
    volumes:
     - sensorsfs:/sys/fs/cgroup
    restart: always
    privileged: true
    
