version: '2'
services:
  mosquitto:
    image: migruiz/climav2-queue-rpi3
    container_name: climaV2-queue
    volumes:
        - sensorsfs:/sys/fs/cgroup
    ports:
     - "8883:8883"
    restart: always
    
    
   sensors:
    image: migruiz/climav2-sensors-rpi3
    container_name: climav2-sensors
    volumes:
     - sensorsfs:/sys/fs/cgroup
    environment:
        MQTTServer : mqtt://192.168.0.137
        NODEID : 1
    restart: always
    privileged: true
    
