version: '2'
services:
  sensors:
    image: migruiz/clima-sensors-rpi3:r1
    container_name: clima-sensors
    environment:
        TEMPQUEUEURL : amqp://pi:pi@192.168.0.96
        NODEID : 4
    volumes:
        - sensorsfs:/sys/fs/cgroup
    restart: always
    privileged: true
    
